project_id = "fhwqsocjvpbghptvzekk"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false

[functions.auto-clock-out]
verify_jwt = false

[functions.verify-invite]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false
