// Core types for the modular estimate calculator system

/**
 * User-defined extra item for custom costs not covered by standard modules
 */
export interface ExtraItem {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  rate: number;
  total: number;
}

/**
 * Represents a question asked within a component module
 */
export interface ComponentQuestion {
  id: string;
  type: 'number' | 'select' | 'boolean' | 'text' | 'currency';
  label: string;
  helpText?: string;
  defaultValue?: string | number | boolean;
  options?: Array<{ value: string; label: string; priceKey?: string }>;
  priceListKey?: string;  // Links to price list item for auto-fill
  unit?: string;          // Display unit (e.g., 'hrs', 'm³', '$')
  min?: number;
  max?: number;
  step?: number;
  /** Conditional display - can access both answers and scopeData */
  showIf?: (answers: Record<string, any>, scopeData?: Record<string, any>) => boolean;
  required?: boolean;
  placeholder?: string;
  
  /**
   * If true, this field requires explicit user input and should not be prefilled with a default.
   * Fields with this flag will be prominently displayed when empty to ensure users notice them.
   */
  requiresUserInput?: boolean;
  
  /** 
   * Section label - displays a visual separator/header before this question
   * Used to group related questions visually
   */
  sectionLabel?: string;
  
  /**
   * Get scope-specific label for this question
   * Returns custom label based on scope (e.g., "Edge Thickening" for driveway)
   */
  getScopeLabel?: (scopeId: string) => string;
  
  /**
   * Get scope-specific section label
   * Returns custom section label based on scope
   */
  getScopeSectionLabel?: (scopeId: string) => string;
  
  /** 
   * Function to derive this field's value from scope data, module answers, and price map
   * Returns undefined if no auto-fill should occur
   */
  deriveFrom?: (
    scopeData: Record<string, any>,
    moduleAnswers: Record<string, any>,
    priceMap: PriceMap
  ) => any | undefined;
  
  /**
   * If true, user cannot edit the derived value (read-only)
   * If false (default), user can override the derived value
   */
  derivedReadOnly?: boolean;
}

/**
 * A single line item in the cost breakdown
 */
export interface CostLineItem {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  total: number;
  category: 'labour' | 'labour-prep' | 'labour-place' | 'materials' | 'plant' | 'subcontractor' | 'other';
}

/**
 * Result of calculating a component's costs
 */
export interface ComponentCost {
  moduleId: string;
  moduleName: string;
  lineItems: CostLineItem[];
  subtotal: number;
  exclusions: ExclusionItem[];
}

/**
 * An exclusion clause generated by a module
 */
export interface ExclusionItem {
  id: string;
  text: string;
  moduleId: string;
}

/**
 * Price map type for looking up prices by category and item code
 */
export type PriceMap = Record<string, Record<string, number>>;

/**
 * A reusable component module that can be shared across scopes
 */
export interface EstimateModule {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  questions: ComponentQuestion[];
  
  /**
   * Calculate costs based on answers and price list
   * @param answers - User's answers to this module's questions
   * @param priceMap - Price lookup map from business price list
   * @param scopeData - Additional data from scope-level questions (e.g., volume, area)
   */
  calculate: (
    answers: Record<string, any>,
    priceMap: PriceMap,
    scopeData: Record<string, any>
  ) => ComponentCost;
  
  /**
   * Get list of exclusions based on disabled features and scope data
   */
  getExclusions: (answers: Record<string, any>, scopeData?: Record<string, any>) => ExclusionItem[];
  
  /**
   * Validate that all required questions are answered
   */
  validate: (answers: Record<string, any>) => { valid: boolean; errors: string[] };
}

/**
 * Scope-level question (e.g., number of piers, slab dimensions)
 */
export interface ScopeQuestion extends ComponentQuestion {
  affectsModules?: string[];  // Which modules use this value
  calculatesVolume?: boolean; // Does this contribute to concrete volume
}

/**
 * Individual measurement area for multi-area scopes
 */
export interface MeasurementArea {
  id: string;
  name: string;
  length: number;
  width: number;
  /** Per-area thickness override in mm. When defined and usePerAreaThickness is true, this overrides the shared scope-level thickness */
  thickness?: number;
  /** If true, this area was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured area from takeoff (more accurate than length x width) */
  _actualArea?: number;
  /** Actual measured perimeter from takeoff */
  _actualPerimeter?: number;
  
  // Per-area reinforcement settings
  reo_type?: 'none' | 'mesh' | 'bar' | 'fiber';
  mesh_type?: string;
  mesh_layers?: number;  // 1 or 2 - number of mesh layers
  mesh_type_top?: string;  // Top layer mesh type (when mesh_layers > 1)
  mesh_price?: number;     // Price override per sheet (from price list, editable)
  mesh_price_top?: number; // Price override for top layer (when mesh_layers > 1)
  bar_size?: string;
  bar_spacing?: string;
  bar_layers?: string;
  
  // Per-area bar chair settings
  chairs_enabled?: boolean;
  chair_type?: string;       // e.g., '7590C'
  chairs_per_m2?: number;    // chairs per square metre
  chair_price_per_bag?: number; // price per 100
  layer_chairs_enabled?: boolean; // chairs between mesh layers
  layer_chair_type?: string;      // e.g., '7590C' - chair type for top layer
  layer_chairs_per_m2?: number;   // layer chairs per m²
  layer_chair_price?: number;     // price per 100 for layer chairs
}

/**
 * Individual pier within a pier group
 * @deprecated Individual pier items no longer have unique names - use PierGroup.quantity instead
 */
export interface PierItem {
  id: string;
  name: string;
  diameter: number;  // mm
  depth: number;     // mm
  /** If true, this pier was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Per-pier reinforcement overrides
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * A group of identical piers with shared dimensions and reinforcement
 * All piers within a group have the same specifications
 */
export interface PierGroup {
  id: string;
  name: string;           // Group name, e.g., "Footing Piers"
  quantity: number;       // Number of identical piers in this group
  diameter: number;       // mm - shared diameter for all piers in group
  depth: number;          // mm - shared depth for all piers in group
  /** If true, this group was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Legacy: array of individual piers (for backwards compatibility)
  piers?: PierItem[];
  
  // Group-level reinforcement settings
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * Individual pier configuration for multi-pier scopes
 * @deprecated Use PierGroup and PierItem instead for grouped piers
 */
export interface PierConfig {
  id: string;
  name: string;
  quantity: number;
  diameter: number;  // mm
  depth: number;     // mm
  /** If true, this pier config was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Per-pier reinforcement overrides
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * Pad footing group - all footings in a group share the same dimensions
 */
export interface PadFootingGroup {
  id: string;
  name: string;           // Group name, e.g., "Column A Footings"
  quantity: number;       // Number of identical pad footings in this group
  length: number;         // mm - shared length for all pads in group
  width: number;          // mm - shared width for all pads in group
  depth: number;          // mm - shared depth for all pads in group
  /** If true, this group was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Group-level reinforcement settings
  has_bottom_reo?: boolean;
  bottom_a_size?: string;
  bottom_a_centres?: number;
  bottom_b_size?: string;
  bottom_b_centres?: number;
  has_top_reo?: boolean;
  top_a_size?: string;
  top_a_centres?: number;
  top_b_size?: string;
  top_b_centres?: number;
  
  // Starter Bars (vertical bars projecting from pad footing)
  has_starters?: boolean;
  starter_count?: number;     // number of starters per pad
  starter_size?: string;      // bar size e.g. 'N16'
  starter_length?: number;    // mm projection length
  
  // Bar Chairs
  chairs_enabled?: boolean;
  chairs_per_sqm?: number;
  chair_price_per_100?: number;
}

/**
 * Individual footing configuration for multi-footing scopes
 */
export interface FootingConfig {
  id: string;
  name: string;
  length: number;    // m
  width: number;     // mm
  depth: number;     // mm
  /** If true, this footing config was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured length from takeoff (more accurate) */
  _actualLength?: number;
  
  // For compatibility with LinearSection (allows unified type handling)
  dimension1?: number;  // mm (width)
  dimension2?: number;  // mm (depth)
  
  // Per-footing reinforcement overrides (matching BeamConfig pattern)
  reo_type?: 'none' | 'trench_mesh' | 'bar' | 'both';
  
  // Trench mesh settings
  tm_type?: string;
  tm_layers?: number;  // 1 or 2 - number of trench mesh layers
  tm_type_top?: string;  // Top layer TM type (when tm_layers > 1)
  tm_price?: number;     // Price override per sheet (from price list, editable)
  tm_price_top?: number; // Price override for top layer (when tm_layers > 1)
  
  // Ligatures
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
  
  // Horizontal reinforcement (additional bars along footing length)
  horizontal_bars?: HorizontalBarConfig[];
  
  // Vertical reinforcement (starter bars projecting from footing)
  vertical_bars?: VerticalBarConfig[];
  
  // Legacy vertical bars toggle (backwards compat)
  add_vertical_bars?: boolean;
  vertical_bar_size?: string;
  vertical_bar_centres?: number;
  
  // Per-footing bar chair settings
  chairs_enabled?: boolean;
  chairs_per_m?: number;         // chairs per linear metre
  chair_price_per_bag?: number;  // price per 25
  layer_chairs_enabled?: boolean; // chairs between TM layers
  layer_chairs_per_m?: number;    // layer chairs per m
  layer_chair_price?: number;     // price per 25 for layer chairs
}

/**
 * Individual linear section configuration for linear scopes (walls, kerbs, strip footings)
 */
export interface LinearSection {
  id: string;
  name: string;
  length: number;      // meters
  dimension1: number;  // mm (width or thickness, depending on scope)
  dimension2: number;  // mm (depth or height, depending on scope)
  /** Whether this footing has a toe (for retaining wall footings) */
  has_toe?: boolean;
  /** Toe width in mm for retaining wall footings */
  toe_width?: number;
  /** Toe depth in mm for retaining wall footings */
  toe_depth?: number;
  /** If true, this section was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured length from takeoff (more accurate) */
  _actualLength?: number;
  
  // Per-section reinforcement settings
  reo_type?: 'none' | 'trench_mesh' | 'bar' | 'both';
  
  // Trench mesh settings
  tm_type?: string;
  tm_layers?: number;  // 1 or 2 - number of trench mesh layers
  tm_type_top?: string;  // Top layer TM type (when tm_layers > 1)
  tm_price?: number;     // Price override per sheet (from price list, editable)
  tm_price_top?: number; // Price override for top layer (when tm_layers > 1)
  
  // Bar reinforcement settings
  bar_size?: string;
  bar_spacing?: string;
  bar_config?: 'bottom' | 'top_bottom';
  
  // Ligatures
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
  
  // Horizontal reinforcement (additional bars along section length)
  horizontal_bars?: HorizontalBarConfig[];
  
  // Vertical reinforcement (starter bars projecting from section)
  vertical_bars?: VerticalBarConfig[];
  
  // Legacy vertical starters (backwards compat)
  add_vertical_bars?: boolean;
  vertical_bar_size?: string;
  vertical_bar_centres?: number;
  
  // Per-section bar chair settings
  chairs_enabled?: boolean;
  chair_type?: string;           // e.g., '2540C', '5065C', '7590C', '100120C', '125150C'
  chairs_per_m?: number;         // chairs per linear metre
  chair_price_per_bag?: number;  // price per 25
  layer_chairs_enabled?: boolean; // chairs between TM layers
  layer_chair_type?: string;      // e.g., '2540C' - chair type for top layer
  layer_chairs_per_m?: number;    // layer chairs per m
  layer_chair_price?: number;     // price per 25 for layer chairs
}

/**
 * Individual beam configuration for multi-beam scopes (raft slabs)
 */
export interface BeamConfig {
  id: string;
  name: string;
  length: number;    // metres
  width: number;     // mm
  depth: number;     // mm
  
  // Per-beam reinforcement settings
  tm_type?: string;
  tm_layers?: number;  // 1 or 2 - number of trench mesh layers
  tm_type_top?: string;  // Top layer TM type (when tm_layers > 1)
  tm_price?: number;     // Price override per sheet (from price list, editable)
  tm_price_top?: number; // Price override for top layer (when tm_layers > 1)
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
  
  // Horizontal reinforcement (additional bars along beam length)
  horizontal_bars?: HorizontalBarConfig[];
  
  // Vertical reinforcement (starter bars projecting from beam)
  vertical_bars?: VerticalBarConfig[];
  
  // Per-beam bar chair settings
  chairs_enabled?: boolean;
  chair_type?: string;           // e.g., '2540C', '5065C', '7590C', '100120C', '125150C'
  chairs_per_m?: number;         // chairs per linear metre
  chair_price_per_bag?: number;  // price per 25
  layer_chairs_enabled?: boolean; // chairs between TM layers
  layer_chair_type?: string;      // e.g., '2540C' - chair type for top layer
  layer_chairs_per_m?: number;    // layer chairs per m
  layer_chair_price?: number;     // price per 25 for layer chairs
}

/**
 * Horizontal bar reinforcement configuration for beams
 */
export interface HorizontalBarConfig {
  id: string;
  bar_size: string;    // e.g., 'N12', 'N16'
  quantity: number;    // number of bars
  position: 'top' | 'bottom';
}

/**
 * Vertical bar reinforcement configuration for beams (starter bars)
 */
export interface VerticalBarConfig {
  id: string;
  bar_size: string;    // e.g., 'N12', 'N16'
  centres: number;     // mm spacing
  length: number;      // mm projection length
}

/**
 * Individual demolition area configuration
 */
export interface DemolitionArea {
  id: string;
  name: string;
  length: number;    // metres
  width: number;     // metres
  thickness: number; // mm (each area can have different thickness)
}

/**
 * Definition of a scope (e.g., Piers, Slab, Driveway)
 */
export interface ScopeDefinition {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  
  /** Scope-level questions (dimensions, quantities, etc.) */
  questions: ScopeQuestion[];
  
  /** Module IDs that this scope uses */
  moduleIds: string[];
  
  /** Calculate total concrete volume from scope answers */
  calculateVolume?: (answers: Record<string, any>) => number;
  
  /** Calculate excavation volume from scope answers (if different from concrete volume) */
  calculateExcavationVolume?: (answers: Record<string, any>) => number;
  
  /** Default exclusions that always apply to this scope */
  defaultExclusions?: ExclusionItem[];
  
  /** If true, allows multiple measurement areas within this scope */
  supportsMultipleAreas?: boolean;
  
  /** Label for the areas section (e.g., "Driveway Areas") */
  areasLabel?: string;
  
  /** If true, allows multiple pier configurations within this scope */
  supportsMultiplePiers?: boolean;
  
  /** Label for the piers section (e.g., "Pier Configurations") */
  piersLabel?: string;
  
  /** If true, allows multiple footing configurations within this scope */
  supportsMultipleFootings?: boolean;
  
  /** Label for the footings section (e.g., "Footing Sections") */
  footingsLabel?: string;
  
  /** If true, allows multiple linear section configurations (walls, kerbs, strip footings) */
  supportsLinearSections?: boolean;
  
  /** Label for the linear sections (e.g., "Wall Sections") */
  linearSectionsLabel?: string;
  
  /** If true, allows multiple internal beam configurations within this scope */
  supportsMultipleBeams?: boolean;
  
  /** Label for the beams section (e.g., "Internal Stiffening Beams") */
  beamsLabel?: string;
  
  /** If true, allows multiple edge beam configurations within this scope */
  supportsMultipleEdgeBeams?: boolean;
  
  /** Label for the edge beams section (e.g., "Edge Beams") */
  edgeBeamsLabel?: string;
  
  /** If true, allows multiple pad footing group configurations */
  supportsPadGroups?: boolean;
  
  /** Label for the pad footing groups section (e.g., "Pad Footing Groups") */
  padGroupsLabel?: string;
  
  /** Question IDs that should be hidden from standard rendering (managed by multi-input components) */
  hideStandardQuestions?: string[];
}

/**
 * Complete estimate state stored in scope_data
 */
export interface EstimateState {
  scopeId: string;
  scopeAnswers: Record<string, any>;
  moduleAnswers: Record<string, Record<string, any>>;
  calculatedCosts: ComponentCost[];
  exclusions: ExclusionItem[];
  customExclusions: ExclusionItem[];
  marginPercent: number;
  subtotal: number;
  marginAmount: number;
  gst: number;
  total: number;
}

/**
 * Helper to create a price map from price list items
 */
export function createPriceMap(
  items: Array<{ category: string; item_code: string; default_price: number; custom_price?: number | null }>
): PriceMap {
  const map: PriceMap = {};
  
  for (const item of items) {
    if (!map[item.category]) {
      map[item.category] = {};
    }
    // Use custom price if set, otherwise default
    map[item.category][item.item_code] = item.custom_price ?? item.default_price;
  }
  
  return map;
}

/**
 * Get a price from the price map with fallback
 */
export function getPrice(priceMap: PriceMap, category: string, itemCode: string, fallback = 0): number {
  return priceMap[category]?.[itemCode] ?? fallback;
}

/**
 * Round up a volume to the nearest 0.1 m³
 * Used for concrete ordering - always round up to avoid being short
 */
export function roundUpToM3(volume: number): number {
  if (volume <= 0) return 0;
  return Math.ceil(volume * 10) / 10;
}

/**
 * Rebar weight constants (kg per metre)
 */
export const REBAR_WEIGHTS: Record<string, number> = {
  'N10': 0.617,
  'N12': 0.888,
  'N16': 1.58,
  'N20': 2.47,
  'N24': 3.55,
  'N28': 4.83,
  'N32': 6.31,
  'N36': 7.99,
  'N40': 9.86,
  'R10': 0.617,
  'R12': 0.888,
  'R16': 1.58,
  'R20': 2.47,
  'R24': 3.55,
};

/**
 * Standard mesh sheet dimensions
 */
export const MESH_DIMENSIONS = {
  standard: { width: 2.4, length: 6 },  // metres
  ute: { width: 2, length: 4 },
};

/**
 * Excavator capacity (m³/hr) for estimating machine hours
 */
export const EXCAVATOR_CAPACITY: Record<string, number> = {
  'EXC 1.4T': 8,
  'EXC 3.2T': 12,
  'EXC 4T': 15,
  'EXC 6T': 20,
  'EXC 9T': 30,
  'POSI TRACK': 10,
};

/**
 * Material density constants for takeoff calculations
 */
export const MATERIAL_DENSITY = {
  crusherDust: 1.6,  // tonnes per m³
  concrete: 2.4,     // tonnes per m³
  gravel: 1.5,       // tonnes per m³
};

/**
 * Formwork constants for takeoff calculations
 */
export const FORMWORK_CONSTANTS = {
  stakeSpacing: 0.6,        // metres between stakes
  fixingsPerMetre: 2,       // nails/screws per metre
  timberWastePercent: 10,   // 10% waste allowance
};

/**
 * Pump size recommendations based on volume (m³)
 */
export const PUMP_RECOMMENDATIONS = {
  directChute: { maxVolume: 10, label: 'Direct chute may suffice' },
  linePump: { maxVolume: 30, label: 'Line Pump recommended' },
  smallBoom: { maxVolume: 60, label: '32M Boom Pump recommended' },
  largeBoom: { maxVolume: 100, label: '42M+ Boom Pump recommended' },
  multiple: { label: 'Large boom or multiple loads recommended' },
};

/**
 * Individual pump visit configuration for multi-visit pumping
 */
export interface PumpVisit {
  id: string;
  pump_type: string;
  pump_rate: number;
  travel_hours: number;
  pump_hours_on_site: number;
  primer_count: number;
  primer_cost: number;
  offsite_washout: boolean;
  washout_cost: number;
  additional_pumpy: boolean;
  pumpy_rate: number;
}

/**
 * Individual labour placement (pour) configuration
 */
export interface LabourPlacement {
  id: string;
  name?: string;           // Optional pour name (e.g., "Slab Pour 1")
  hourly_rate: number;
  crew_size: number;
  hours: number;           // Hours for this placement
}

/**
 * Individual expansion joint configuration for multi-depth joints
 * Allows specifying different joint depths for slabs with varying thicknesses
 * Includes per-joint dowels and expansion foam configuration
 */
export interface ExpansionJointConfig {
  id: string;
  name?: string;           // Optional label (e.g., "100mm Slab Joints")
  depth: string;           // Joint depth matching slab thickness: '100', '125', '150', '200'
  length: string;          // Joint piece length: '3000' or '6000'
  quantity: number;        // Number of joint pieces
  price_each: number;      // Price per joint piece
  capping_required: boolean;
  capping_type?: string;   // 'EXJ CAP B', 'EXJ CAP G', 'EXJ CAP RBM'
  capping_price_per_m?: number;
  
  // Takeoff measurement fields
  total_length_m?: number;      // Total measured length in meters (from takeoff or manual)
  measured_on_plans?: boolean;  // Flag indicating if length came from takeoff
  
  // Dowels configuration
  dowels_required?: boolean;
  dowel_size?: string;     // 'R12-300 GAL', 'R12-450 GAL', 'R16-300 GAL', etc.
  dowel_calculation_method?: 'manual' | 'spacing';
  dowel_count?: number;    // Manual count
  connection_length?: number; // metres (when using spacing method)
  dowel_spacing?: string;  // '200', '250', '300', '400', '450', '600'
  dowel_price_each?: number;
  chemical_anchor?: boolean;
  chemical_cartridges?: number;
  chemical_price?: number;
  
  // Expansion foam configuration
  foam_required?: boolean;
  foam_type?: string;      // 'sticky_back' or 'standard'
  foam_height?: string;    // '50', '75', '100', '125', '150', '200', '250', '300'
  foam_rolls?: number;
  foam_roll_price?: number;
}

/**
 * Individual control joint (saw cut) configuration for multi-row control joints
 * Allows specifying multiple control joint configurations with per-joint caulking toggle
 */
export interface ControlJointConfig {
  id: string;
  name?: string;                    // Optional label (e.g., "Garage Floor Cuts")
  
  // Length - manual or measured from takeoff
  total_length_m: number;           // Total saw cut length in metres
  measured_on_plans?: boolean;      // Flag if measured from takeoff
  
  // Saw cutting pricing
  pricing_method: 'per_metre' | 'hourly';
  price_per_m?: number;             // Price per metre (when per_metre)
  hours?: number;                   // Hours (when hourly)
  hourly_rate?: number;             // Hourly rate (when hourly)
  
  // Caulking - per joint toggle
  caulking_required: boolean;
  caulking_price_per_m?: number;
}
