// Core types for the modular estimate calculator system

/**
 * Represents a question asked within a component module
 */
export interface ComponentQuestion {
  id: string;
  type: 'number' | 'select' | 'boolean' | 'text' | 'currency';
  label: string;
  helpText?: string;
  defaultValue?: string | number | boolean;
  options?: Array<{ value: string; label: string; priceKey?: string }>;
  priceListKey?: string;  // Links to price list item for auto-fill
  unit?: string;          // Display unit (e.g., 'hrs', 'm³', '$')
  min?: number;
  max?: number;
  step?: number;
  /** Conditional display - can access both answers and scopeData */
  showIf?: (answers: Record<string, any>, scopeData?: Record<string, any>) => boolean;
  required?: boolean;
  placeholder?: string;
  
  /** 
   * Section label - displays a visual separator/header before this question
   * Used to group related questions visually
   */
  sectionLabel?: string;
  
  /** 
   * Function to derive this field's value from scope data, module answers, and price map
   * Returns undefined if no auto-fill should occur
   */
  deriveFrom?: (
    scopeData: Record<string, any>,
    moduleAnswers: Record<string, any>,
    priceMap: PriceMap
  ) => any | undefined;
  
  /**
   * If true, user cannot edit the derived value (read-only)
   * If false (default), user can override the derived value
   */
  derivedReadOnly?: boolean;
}

/**
 * A single line item in the cost breakdown
 */
export interface CostLineItem {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  total: number;
  category: 'labour' | 'labour-prep' | 'labour-place' | 'materials' | 'plant' | 'subcontractor' | 'other';
}

/**
 * Result of calculating a component's costs
 */
export interface ComponentCost {
  moduleId: string;
  moduleName: string;
  lineItems: CostLineItem[];
  subtotal: number;
  exclusions: ExclusionItem[];
}

/**
 * An exclusion clause generated by a module
 */
export interface ExclusionItem {
  id: string;
  text: string;
  moduleId: string;
}

/**
 * Price map type for looking up prices by category and item code
 */
export type PriceMap = Record<string, Record<string, number>>;

/**
 * A reusable component module that can be shared across scopes
 */
export interface EstimateModule {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  questions: ComponentQuestion[];
  
  /**
   * Calculate costs based on answers and price list
   * @param answers - User's answers to this module's questions
   * @param priceMap - Price lookup map from business price list
   * @param scopeData - Additional data from scope-level questions (e.g., volume, area)
   */
  calculate: (
    answers: Record<string, any>,
    priceMap: PriceMap,
    scopeData: Record<string, any>
  ) => ComponentCost;
  
  /**
   * Get list of exclusions based on disabled features and scope data
   */
  getExclusions: (answers: Record<string, any>, scopeData?: Record<string, any>) => ExclusionItem[];
  
  /**
   * Validate that all required questions are answered
   */
  validate: (answers: Record<string, any>) => { valid: boolean; errors: string[] };
}

/**
 * Scope-level question (e.g., number of piers, slab dimensions)
 */
export interface ScopeQuestion extends ComponentQuestion {
  affectsModules?: string[];  // Which modules use this value
  calculatesVolume?: boolean; // Does this contribute to concrete volume
}

/**
 * Individual measurement area for multi-area scopes
 */
export interface MeasurementArea {
  id: string;
  name: string;
  length: number;
  width: number;
  /** If true, this area was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured area from takeoff (more accurate than length x width) */
  _actualArea?: number;
  /** Actual measured perimeter from takeoff */
  _actualPerimeter?: number;
  
  // Per-area reinforcement settings
  reo_type?: 'none' | 'mesh' | 'bar' | 'fiber';
  mesh_type?: string;
  bar_size?: string;
  bar_spacing?: string;
  bar_layers?: string;
}

/**
 * Individual pier within a pier group
 * @deprecated Individual pier items no longer have unique names - use PierGroup.quantity instead
 */
export interface PierItem {
  id: string;
  name: string;
  diameter: number;  // mm
  depth: number;     // mm
  /** If true, this pier was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Per-pier reinforcement overrides
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * A group of identical piers with shared dimensions and reinforcement
 * All piers within a group have the same specifications
 */
export interface PierGroup {
  id: string;
  name: string;           // Group name, e.g., "Footing Piers"
  quantity: number;       // Number of identical piers in this group
  diameter: number;       // mm - shared diameter for all piers in group
  depth: number;          // mm - shared depth for all piers in group
  /** If true, this group was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Legacy: array of individual piers (for backwards compatibility)
  piers?: PierItem[];
  
  // Group-level reinforcement settings
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * Individual pier configuration for multi-pier scopes
 * @deprecated Use PierGroup and PierItem instead for grouped piers
 */
export interface PierConfig {
  id: string;
  name: string;
  quantity: number;
  diameter: number;  // mm
  depth: number;     // mm
  /** If true, this pier config was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Per-pier reinforcement overrides
  has_starters?: boolean;
  starter_count?: number;
  starter_size?: string;
  starter_length?: number;
  is_reinforced?: boolean;
  vertical_bars_count?: number;
  vertical_bar_size?: string;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * Pad footing group - all footings in a group share the same dimensions
 */
export interface PadFootingGroup {
  id: string;
  name: string;           // Group name, e.g., "Column A Footings"
  quantity: number;       // Number of identical pad footings in this group
  length: number;         // mm - shared length for all pads in group
  width: number;          // mm - shared width for all pads in group
  depth: number;          // mm - shared depth for all pads in group
  /** If true, this group was imported from plan takeoff */
  _fromTakeoff?: boolean;
  
  // Group-level reinforcement settings
  has_bottom_reo?: boolean;
  bottom_a_size?: string;
  bottom_a_centres?: number;
  bottom_b_size?: string;
  bottom_b_centres?: number;
  has_top_reo?: boolean;
  top_a_size?: string;
  top_a_centres?: number;
  top_b_size?: string;
  top_b_centres?: number;
}

/**
 * Individual footing configuration for multi-footing scopes
 */
export interface FootingConfig {
  id: string;
  name: string;
  length: number;    // m
  width: number;     // mm
  depth: number;     // mm
  /** If true, this footing config was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured length from takeoff (more accurate) */
  _actualLength?: number;
  
  // Per-footing reinforcement overrides
  reo_type?: 'none' | 'trench_mesh' | 'bar' | 'both';
  tm_type?: string;
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
  add_vertical_bars?: boolean;
  vertical_bar_size?: string;
  vertical_bar_centres?: number;
}

/**
 * Individual linear section configuration for linear scopes (walls, kerbs, strip footings)
 */
export interface LinearSection {
  id: string;
  name: string;
  length: number;      // meters
  dimension1: number;  // mm (width or thickness, depending on scope)
  dimension2: number;  // mm (depth or height, depending on scope)
  /** If true, this section was imported from plan takeoff */
  _fromTakeoff?: boolean;
  /** Actual measured length from takeoff (more accurate) */
  _actualLength?: number;
  
  // Per-section reinforcement overrides
  reo_type?: 'none' | 'trench_mesh' | 'bar' | 'both';
  tm_type?: string;
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
  add_vertical_bars?: boolean;
  vertical_bar_size?: string;
  vertical_bar_centres?: number;
}

/**
 * Individual beam configuration for multi-beam scopes (raft slabs)
 */
export interface BeamConfig {
  id: string;
  name: string;
  length: number;    // metres
  width: number;     // mm
  depth: number;     // mm
  
  // Per-beam reinforcement settings
  tm_type?: string;
  add_ligs?: boolean;
  lig_size?: string;
  lig_centres?: number;
}

/**
 * Individual demolition area configuration
 */
export interface DemolitionArea {
  id: string;
  name: string;
  length: number;    // metres
  width: number;     // metres
  thickness: number; // mm (each area can have different thickness)
}

/**
 * Definition of a scope (e.g., Piers, Slab, Driveway)
 */
export interface ScopeDefinition {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  
  /** Scope-level questions (dimensions, quantities, etc.) */
  questions: ScopeQuestion[];
  
  /** Module IDs that this scope uses */
  moduleIds: string[];
  
  /** Calculate total concrete volume from scope answers */
  calculateVolume?: (answers: Record<string, any>) => number;
  
  /** Calculate excavation volume from scope answers (if different from concrete volume) */
  calculateExcavationVolume?: (answers: Record<string, any>) => number;
  
  /** Default exclusions that always apply to this scope */
  defaultExclusions?: ExclusionItem[];
  
  /** If true, allows multiple measurement areas within this scope */
  supportsMultipleAreas?: boolean;
  
  /** Label for the areas section (e.g., "Driveway Areas") */
  areasLabel?: string;
  
  /** If true, allows multiple pier configurations within this scope */
  supportsMultiplePiers?: boolean;
  
  /** Label for the piers section (e.g., "Pier Configurations") */
  piersLabel?: string;
  
  /** If true, allows multiple footing configurations within this scope */
  supportsMultipleFootings?: boolean;
  
  /** Label for the footings section (e.g., "Footing Sections") */
  footingsLabel?: string;
  
  /** If true, allows multiple linear section configurations (walls, kerbs, strip footings) */
  supportsLinearSections?: boolean;
  
  /** Label for the linear sections (e.g., "Wall Sections") */
  linearSectionsLabel?: string;
  
  /** If true, allows multiple internal beam configurations within this scope */
  supportsMultipleBeams?: boolean;
  
  /** Label for the beams section (e.g., "Internal Stiffening Beams") */
  beamsLabel?: string;
  
  /** If true, allows multiple edge beam configurations within this scope */
  supportsMultipleEdgeBeams?: boolean;
  
  /** Label for the edge beams section (e.g., "Edge Beams") */
  edgeBeamsLabel?: string;
  
  /** If true, allows multiple pad footing group configurations */
  supportsPadGroups?: boolean;
  
  /** Label for the pad footing groups section (e.g., "Pad Footing Groups") */
  padGroupsLabel?: string;
  
  /** Question IDs that should be hidden from standard rendering (managed by multi-input components) */
  hideStandardQuestions?: string[];
}

/**
 * Complete estimate state stored in scope_data
 */
export interface EstimateState {
  scopeId: string;
  scopeAnswers: Record<string, any>;
  moduleAnswers: Record<string, Record<string, any>>;
  calculatedCosts: ComponentCost[];
  exclusions: ExclusionItem[];
  customExclusions: ExclusionItem[];
  marginPercent: number;
  subtotal: number;
  marginAmount: number;
  gst: number;
  total: number;
}

/**
 * Helper to create a price map from price list items
 */
export function createPriceMap(
  items: Array<{ category: string; item_code: string; default_price: number; custom_price?: number | null }>
): PriceMap {
  const map: PriceMap = {};
  
  for (const item of items) {
    if (!map[item.category]) {
      map[item.category] = {};
    }
    // Use custom price if set, otherwise default
    map[item.category][item.item_code] = item.custom_price ?? item.default_price;
  }
  
  return map;
}

/**
 * Get a price from the price map with fallback
 */
export function getPrice(priceMap: PriceMap, category: string, itemCode: string, fallback = 0): number {
  return priceMap[category]?.[itemCode] ?? fallback;
}

/**
 * Round up a volume to the nearest 0.1 m³
 * Used for concrete ordering - always round up to avoid being short
 */
export function roundUpToM3(volume: number): number {
  if (volume <= 0) return 0;
  return Math.ceil(volume * 10) / 10;
}

/**
 * Rebar weight constants (kg per metre)
 */
export const REBAR_WEIGHTS: Record<string, number> = {
  'N10': 0.617,
  'N12': 0.888,
  'N16': 1.58,
  'N20': 2.47,
  'N24': 3.55,
  'N28': 4.83,
  'N32': 6.31,
  'N36': 7.99,
  'N40': 9.86,
  'R10': 0.617,
  'R12': 0.888,
  'R16': 1.58,
  'R20': 2.47,
  'R24': 3.55,
};

/**
 * Standard mesh sheet dimensions
 */
export const MESH_DIMENSIONS = {
  standard: { width: 2.4, length: 6 },  // metres
  ute: { width: 2, length: 4 },
};

/**
 * Excavator capacity (m³/hr) for estimating machine hours
 */
export const EXCAVATOR_CAPACITY: Record<string, number> = {
  'EXC 1.4T': 8,
  'EXC 3.2T': 12,
  'EXC 4T': 15,
  'EXC 6T': 20,
  'EXC 9T': 30,
  'POSI TRACK': 10,
};

/**
 * Material density constants for takeoff calculations
 */
export const MATERIAL_DENSITY = {
  crusherDust: 1.6,  // tonnes per m³
  concrete: 2.4,     // tonnes per m³
  gravel: 1.5,       // tonnes per m³
};

/**
 * Formwork constants for takeoff calculations
 */
export const FORMWORK_CONSTANTS = {
  stakeSpacing: 0.6,        // metres between stakes
  fixingsPerMetre: 2,       // nails/screws per metre
  timberWastePercent: 10,   // 10% waste allowance
};

/**
 * Pump size recommendations based on volume (m³)
 */
export const PUMP_RECOMMENDATIONS = {
  directChute: { maxVolume: 10, label: 'Direct chute may suffice' },
  linePump: { maxVolume: 30, label: 'Line Pump recommended' },
  smallBoom: { maxVolume: 60, label: '32M Boom Pump recommended' },
  largeBoom: { maxVolume: 100, label: '42M+ Boom Pump recommended' },
  multiple: { label: 'Large boom or multiple loads recommended' },
};
