// Core types for the modular estimate calculator system

/**
 * Represents a question asked within a component module
 */
export interface ComponentQuestion {
  id: string;
  type: 'number' | 'select' | 'boolean' | 'text' | 'currency';
  label: string;
  helpText?: string;
  defaultValue?: string | number | boolean;
  options?: Array<{ value: string; label: string; priceKey?: string }>;
  priceListKey?: string;  // Links to price list item for auto-fill
  unit?: string;          // Display unit (e.g., 'hrs', 'm³', '$')
  min?: number;
  max?: number;
  step?: number;
  showIf?: (answers: Record<string, any>) => boolean;  // Conditional display
  required?: boolean;
  placeholder?: string;
  
  /** 
   * Function to derive this field's value from scope data, module answers, and price map
   * Returns undefined if no auto-fill should occur
   */
  deriveFrom?: (
    scopeData: Record<string, any>,
    moduleAnswers: Record<string, any>,
    priceMap: PriceMap
  ) => any | undefined;
  
  /**
   * If true, user cannot edit the derived value (read-only)
   * If false (default), user can override the derived value
   */
  derivedReadOnly?: boolean;
}

/**
 * A single line item in the cost breakdown
 */
export interface CostLineItem {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  total: number;
  category: 'labour' | 'labour-prep' | 'labour-place' | 'materials' | 'plant' | 'subcontractor' | 'other';
}

/**
 * Result of calculating a component's costs
 */
export interface ComponentCost {
  moduleId: string;
  moduleName: string;
  lineItems: CostLineItem[];
  subtotal: number;
  exclusions: ExclusionItem[];
}

/**
 * An exclusion clause generated by a module
 */
export interface ExclusionItem {
  id: string;
  text: string;
  moduleId: string;
}

/**
 * Price map type for looking up prices by category and item code
 */
export type PriceMap = Record<string, Record<string, number>>;

/**
 * A reusable component module that can be shared across scopes
 */
export interface EstimateModule {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  questions: ComponentQuestion[];
  
  /**
   * Calculate costs based on answers and price list
   * @param answers - User's answers to this module's questions
   * @param priceMap - Price lookup map from business price list
   * @param scopeData - Additional data from scope-level questions (e.g., volume, area)
   */
  calculate: (
    answers: Record<string, any>,
    priceMap: PriceMap,
    scopeData: Record<string, any>
  ) => ComponentCost;
  
  /**
   * Get list of exclusions based on disabled features
   */
  getExclusions: (answers: Record<string, any>) => ExclusionItem[];
  
  /**
   * Validate that all required questions are answered
   */
  validate: (answers: Record<string, any>) => { valid: boolean; errors: string[] };
}

/**
 * Scope-level question (e.g., number of piers, slab dimensions)
 */
export interface ScopeQuestion extends ComponentQuestion {
  affectsModules?: string[];  // Which modules use this value
  calculatesVolume?: boolean; // Does this contribute to concrete volume
}

/**
 * Individual measurement area for multi-area scopes
 */
export interface MeasurementArea {
  id: string;
  name: string;
  length: number;
  width: number;
}

/**
 * Individual pier configuration for multi-pier scopes
 */
export interface PierConfig {
  id: string;
  name: string;
  quantity: number;
  diameter: number;  // mm
  depth: number;     // mm
}

/**
 * Individual footing configuration for multi-footing scopes
 */
export interface FootingConfig {
  id: string;
  name: string;
  length: number;    // m
  width: number;     // mm
  depth: number;     // mm
}

/**
 * Individual beam configuration for multi-beam scopes (raft slabs)
 */
export interface BeamConfig {
  id: string;
  name: string;
  length: number;    // metres
  width: number;     // mm
  depth: number;     // mm
}

/**
 * Definition of a scope (e.g., Piers, Slab, Driveway)
 */
export interface ScopeDefinition {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  
  /** Scope-level questions (dimensions, quantities, etc.) */
  questions: ScopeQuestion[];
  
  /** Module IDs that this scope uses */
  moduleIds: string[];
  
  /** Calculate total concrete volume from scope answers */
  calculateVolume?: (answers: Record<string, any>) => number;
  
  /** Default exclusions that always apply to this scope */
  defaultExclusions?: ExclusionItem[];
  
  /** If true, allows multiple measurement areas within this scope */
  supportsMultipleAreas?: boolean;
  
  /** Label for the areas section (e.g., "Driveway Areas") */
  areasLabel?: string;
  
  /** If true, allows multiple pier configurations within this scope */
  supportsMultiplePiers?: boolean;
  
  /** Label for the piers section (e.g., "Pier Configurations") */
  piersLabel?: string;
  
  /** If true, allows multiple footing configurations within this scope */
  supportsMultipleFootings?: boolean;
  
  /** Label for the footings section (e.g., "Footing Sections") */
  footingsLabel?: string;
  
  /** If true, allows multiple internal beam configurations within this scope */
  supportsMultipleBeams?: boolean;
  
  /** Label for the beams section (e.g., "Internal Stiffening Beams") */
  beamsLabel?: string;
}

/**
 * Complete estimate state stored in scope_data
 */
export interface EstimateState {
  scopeId: string;
  scopeAnswers: Record<string, any>;
  moduleAnswers: Record<string, Record<string, any>>;
  calculatedCosts: ComponentCost[];
  exclusions: ExclusionItem[];
  customExclusions: ExclusionItem[];
  marginPercent: number;
  subtotal: number;
  marginAmount: number;
  gst: number;
  total: number;
}

/**
 * Helper to create a price map from price list items
 */
export function createPriceMap(
  items: Array<{ category: string; item_code: string; default_price: number; custom_price?: number | null }>
): PriceMap {
  const map: PriceMap = {};
  
  for (const item of items) {
    if (!map[item.category]) {
      map[item.category] = {};
    }
    // Use custom price if set, otherwise default
    map[item.category][item.item_code] = item.custom_price ?? item.default_price;
  }
  
  return map;
}

/**
 * Get a price from the price map with fallback
 */
export function getPrice(priceMap: PriceMap, category: string, itemCode: string, fallback = 0): number {
  return priceMap[category]?.[itemCode] ?? fallback;
}

/**
 * Rebar weight constants (kg per metre)
 */
export const REBAR_WEIGHTS: Record<string, number> = {
  'N10': 0.617,
  'N12': 0.888,
  'N16': 1.58,
  'N20': 2.47,
  'N24': 3.55,
  'N28': 4.83,
  'N32': 6.31,
  'N36': 7.99,
  'N40': 9.86,
  'R10': 0.617,
  'R12': 0.888,
  'R16': 1.58,
  'R20': 2.47,
  'R24': 3.55,
};

/**
 * Standard mesh sheet dimensions
 */
export const MESH_DIMENSIONS = {
  standard: { width: 2.4, length: 6 },  // metres
  ute: { width: 2, length: 4 },
};

/**
 * Excavator capacity (m³/hr) for estimating machine hours
 */
export const EXCAVATOR_CAPACITY: Record<string, number> = {
  'EXC 1.4T': 8,
  'EXC 3.2T': 12,
  'EXC 4T': 15,
  'EXC 6T': 20,
  'EXC 9T': 30,
  'POSI TRACK': 10,
};

/**
 * Material density constants for takeoff calculations
 */
export const MATERIAL_DENSITY = {
  crusherDust: 1.6,  // tonnes per m³
  concrete: 2.4,     // tonnes per m³
  gravel: 1.5,       // tonnes per m³
};

/**
 * Formwork constants for takeoff calculations
 */
export const FORMWORK_CONSTANTS = {
  stakeSpacing: 0.6,        // metres between stakes
  fixingsPerMetre: 2,       // nails/screws per metre
  timberWastePercent: 10,   // 10% waste allowance
};

/**
 * Pump size recommendations based on volume (m³)
 */
export const PUMP_RECOMMENDATIONS = {
  directChute: { maxVolume: 10, label: 'Direct chute may suffice' },
  linePump: { maxVolume: 30, label: 'Line Pump recommended' },
  smallBoom: { maxVolume: 60, label: '32M Boom Pump recommended' },
  largeBoom: { maxVolume: 100, label: '42M+ Boom Pump recommended' },
  multiple: { label: 'Large boom or multiple loads recommended' },
};
